
# FROM argument for base image running enviroment
FROM node:alpine

# COPY this will copy the all the file from the specified path
COPY . /first-docker-run

# We can set the working directory also
WORKDIR /first-docker-run

# This will helps to run the given command after all setting

CMD node index.js